Let's start with generating a doubly stochatisc matrix!

In [11]:
import numpy as np
import scipy.optimize
rng = np.random.default_rng()
non_square_random = np.pad(rng.random((2,3,)), pad_width=((0,1),(0,0)))

rows, cols = scipy.optimize.linear_sum_assignment(-non_square_random)
rows, cols

(array([0, 1, 2]), array([1, 0, 2]))

Now let's doo the S-K algo:

In [182]:
transp = non_square_random.T
sumed = np.sum(transp, axis=0)

a = np.zeros(non_square_random.shape)
np.divide(non_square_random.T, np.sum(non_square_random.T, axis=0),out=a, where= np.sum(non_square_random.T, axis=0)!=0)
a

array([[0.41143145, 0.3419762 , 0.        ],
       [0.25344069, 0.61968204, 0.        ],
       [0.33512786, 0.03834176, 0.        ]])

In [244]:
for i in range(10):
    a = np.zeros(non_square_random.shape)
    np.divide(non_square_random.T, np.sum(non_square_random.T, axis=0),out=a, where= np.sum(non_square_random.T, axis=0)!=0)
    print(a.T)
    b = np.zeros(non_square_random.shape)
    np.divide(a.T,np.sum(a.T, axis=0), out=b, where= np.sum(a.T, axis=0)!=0)
    print(b)
    non_square_random = b
non_square_random.sum(axis=1)

[[0.29280844 0.14017587 0.56701569]
 [0.37385822 0.5264908  0.09965098]
 [0.         0.         0.        ]]
[[0.43921266 0.21026381 0.85052353]
 [0.56078734 0.78973619 0.14947647]
 [0.         0.         0.        ]]
[[0.29280844 0.14017587 0.56701569]
 [0.37385822 0.5264908  0.09965098]
 [0.         0.         0.        ]]
[[0.43921266 0.21026381 0.85052353]
 [0.56078734 0.78973619 0.14947647]
 [0.         0.         0.        ]]
[[0.29280844 0.14017587 0.56701569]
 [0.37385822 0.5264908  0.09965098]
 [0.         0.         0.        ]]
[[0.43921266 0.21026381 0.85052353]
 [0.56078734 0.78973619 0.14947647]
 [0.         0.         0.        ]]
[[0.29280844 0.14017587 0.56701569]
 [0.37385822 0.5264908  0.09965098]
 [0.         0.         0.        ]]
[[0.43921266 0.21026381 0.85052353]
 [0.56078734 0.78973619 0.14947647]
 [0.         0.         0.        ]]
[[0.29280844 0.14017587 0.56701569]
 [0.37385822 0.5264908  0.09965098]
 [0.         0.         0.        ]]
[[0.43921266 0.2102

array([1.5, 1.5, 0. ])